### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by foxycode** [WebChemistry/forms-doctrine#2]
I'm not sure how to use this with forms. Current version of `WebChemistry\Forms\Form` doesn't have `setDoctrine` method. I hoped that registering extension will help, I saw inject method in code, but after `setEntity` call I get error. I am using latest Nette 2.4 packages.

Also, both `WebChemistry/forms-doctrine` and `WebChemistry/forms` have DI extensions named differently than in docs.

**Comment by MartkCz** [comment]
WebChemistry\Forms\Form inject doctrine via WebChemistry\Forms\Factory\FormFactory. This documentation is outdated, because Form use injectComponents instead of setDoctrine. Now, I use often this helper in repository.

**Comment by foxycode** [comment]
@MartkCz I saw `injectComponents` method in code, but it probably isn't called. I have both extensions registered:
```php
extensions:
    form: WebChemistry\Forms\DI\FormsExtension
    - WebChemistry\Forms\DI\DoctrineExtension
form:
    factories:
        default: WebChemistry\Forms\Factory\FormFactory
```
I also tried to switch them, so DoctrineExtension is first, but doesn't work either.

When I call `setEntity`, I get this error: http://i.imgur.com/IAzLVCB.png
My forms looks like this:
```php
public function create($datacenter = NULL)
{
    $form = new \WebChemistry\Forms\Form;
    $form->addHidden('datacenterId');
    $form->addText('name', 'Název');
    $form->addText('resolvers', 'DNS servery');
    $form->addSubmit('submit', 'Uložit');

    if ($datacenter) {
        $form->setEntity($datacenter);
    }

    $form->onSuccess[] = [$this, 'formSuccess'];

    return $form;
}
```

I found that this exception is thrown here: https://github.com/WebChemistry/forms/blob/35f90cd553c41a0ff41d3c0e3ce3ae87ef3b16a9/src/Form.php#L57 if `Doctrine` is not properly injected. I use both packages from dev-master.

**Comment by MartkCz** [comment]
You must inject factory and use it.

```php
        private $factory;

	public function __construct(WebChemistry\Forms\Factory\FormFactory $factory) {
		$this->factory;
	}

	public function create($datacenter = NULL) {
		$form = $this->factory->create();
		
		// ...
		
		return $form;
	}
```

Or use [WebChemistry\Forms\Control](https://github.com/WebChemistry/forms/blob/master/src/Control.php):

```php
class MyForms extends WebChemistry\Forms\Control {

	public function create($datacenter = NULL) {
		$form = $this->getForm();

		// ...

		return $form;
	}

	// other forms

}
```

**Comment by foxycode** [comment]
@MartkCz This works. Many thanks.
